source 'https://github.com/forestfsl/SegmentSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'SLWebEngine_Example' do
  pod 'SLWebEngine', :path => '../'
  pod 'CTMediatoKit','~> 0.0.2'

#  target 'SLWebEngine_Tests' do
#    inherit! :search_paths
#
#
#  end
end
